// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID     *int   `json:"id"`
	Tittle string `json:"tittle"`
	Author string `json:"author"`
	Status bool   `json:"status"`
}

type LoginResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Token   string `json:"token"`
	User    *User  `json:"User"`
}

type NewBook struct {
	Tittle string `json:"tittle"`
	Author string `json:"author"`
	Status bool   `json:"status"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Product struct {
	ID    *int  `json:"id"`
	Price int   `json:"price"`
	User  *User `json:"user"`
}

type SuccessResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type User struct {
	ID       *int   `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
